dummy_currency_converter:
    resource: "@DummyCurrencyConverterBundle/Controller/"
    type:     annotation
    prefix:   /

currency_converter:
    resource: "@CurrencyConverterBundle/Controller/"
    type:     annotation
    prefix:   /

merchant:
    resource: "@MerchantBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
