# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    output_printer_service:
       class: ReportBundle\Service\OutputPrinterService
    report_service:
       class: ReportBundle\Service\ReportService
       arguments: ["@output_printer_service"]

